# Auto-generiert aus scraper.py — Portal-Domains die übersprungen werden
# Neue Domains einfach unten anhängen

SKIP_DOMAINS = [
    "wikipedia", "gelbeseiten", "yelp", "facebook", "instagram",
    "linkedin", "xing", "kununu", "indeed", "stepstone",
    "google.com/maps", "tripadvisor", "jameda", "doctolib",
    "planity.com", "treatwell.de", "11880.com",
    "branchenbuch-schwerin.de", "dasoertliche.de", "bundes-telefonbuch.de",
    "meinestadt.de", "fmfm.de", "goyellow.de", "golocal.de", "kaufda.de",
    "handwerker-anzeiger.de", "11880-immobilienmakler.com", "dastelefonbuch.de",
    "weshoplocal.de", "misterwhat.de", "plzplz.de",
    "arzt-auskunft.de", "qimeda.de", "docinsider.de", "fachanwalt.de",
    "rechtecheck.de", "rechtsanwalt-regional.de", "sehen.de", "o-pal.de",
    "brillen-sehhilfen.de", "apotheken.de", "ihreapotheken.de",
    "meineapotheke.de", "px.de", "lymphologicum.de", "elektriker.org",
    "maler.org", "dachdecker.com", "dachdecker.org", "auto-werkstatt.de",
    "elektriker-und-elektroniker.de", "elektrikerportal.com",
    "elektriker-24std.de", "elektro-portal.de", "wasserwaermeluft.de",
    "bessere-handwerker.de", "my-hammer.de", "my-profi-maler.de",
    "maler-schwerin.de", "repareo.de", "fahrschulenmap.de", "fahrschulen.de",
    "handelsangebote.de",
    "booking.com", "trivago.de", "hrs.de", "hotel.de",
    "hotel-hostel-unterkunft.de", "kongress.de", "fair-hotels.de",
    "cologne-in.de", "finde-unterkunft.de",
    "schwerin.de", "schweriner.de", "mecklenburg-schwerin.de",
    "wohinheuteschwerin.de",
    "immobilienscout24.de", "gymsider.com", "misterspex.de", "praktiker.de",
    "baeckerei-in-der-naehe.de", "brunch-lunch-dinner.de", "restaurantnet.de",
    "cybo.com", "wanderlog.com", "marcopolo.de", "bvbb.de",
    "volle-deckung.de", "nordkurier.de", "fleurop.de",
    "koepmarkt-schwerin.de", "schlosspark-center.de", "9gg.de", "m-vp.de",
    "11880-steuerberater.com", "wuestenrot-immobilien.de",
    "online-tischreservierung.de", "cafes-in-der-nahe.de", "nochoffen.de",
    "finderr.de", "yellowmap.de", "onlineplan.info", "immosuchmaschine.de",
    "anwaltsverzeichnis.de", "steuer-berater.de", "behoerdenverzeichnis.mv-serviceportal.de",
    "steuerberater-tipps.de",
    "fahrschule-online.de", "blume2000.de", "blumenversand-edelweiss.de",
    "abvz.de", "deutschebiz.de",
    # Nachtschicht 09.02.2026: weitere Portale entdeckt
    "stadtbranchenbuch.com", "branchenbuch24.com", "branchenbuchdeutschland.de",
    "coiffeur-24.de", "total-lokal.de", "exilon.de", "plusbranchenbuch.com",
    "letitshine.de",
    # 21:01 Uhr - Rostock-Scrape Portale
    "rostock-branchenbuch.de", "maurer-portal.de", "blauarbeit.de",
    "bauunternehmer-portal.de",
    "werkenntdenbesten.de", "meinprospekt.de",
    # 14:50 09.02.2026: Bundesweite Online-Ketten (keine lokalen Unternehmen)
    "hoeffner.de", "sb-moebel-boss.de", "moebel-boss.de", "xxxlutz.de",
    "porta.de", "poco.de", "roller.de", "ikea.com", "otto.de",
    "amazon.de", "ebay.de", "real.de", "kaufland.de", "lidl.de", "aldi",
    "mediamarkt.de", "saturn.de", "expert.de", "conrad.de",
    "obi.de", "bauhaus.info", "toom.de", "hornbach.de",
    # 20:16 09.02.2026: Portale/Ketten aus Rostock-Scrape
    "studienkreis.de", "kayak.de", "finanzberater.net", "experten-branchenbuch.de",
    "erstenachhilfe.de", "billiger-mietwagen.de", "anwaltinfos.de",
    "mcmakler.de", "von-poll.com", "jacasa.de", "sprachschule-aktiv.de",
    "musikschulen.de", "starcar.de",
    # 20:42 09.02.2026: Weitere Portale aus Qualitätsprüfung
    "bauunternehmen.org", "schlosser-portal.de", "kennstdueinen.de",
    "dienstleistung-rostock.de", "zimmerer-portal.de", "tischler-schreiner.org",
    "trockenbau-regional.de", "trockenbauunternehmen.net", "fliesenleger.net",
    "schreiner-tischler.de", "starofservice.de", "therapie.de",
    "mobile.de", "sixt.de", "lieferando.de", "tui.com", "visit-mv.com",
    # 22:01 09.02.2026: Portale aus Rostock Full-Scrape Qualitätsprüfung
    "elektriker.biz", "juwelier.org", "stadtbranche.de", "wogibtswas.de",
    "volkswagen.de", "vw-rostock.de",
    # 20:46 09.02.2026: Qualitätsprüfung Rostock (37 neue Portale)
    "raumausstatter.net", "bodenleger.net", "fairgarage.com", "autowerkstatt.net",
    "fahrrad.news", "check24.de", "awhelp24.com", "anwalt.de", "mein-notar.org",
    # 23:01 09.02.2026: Rostock-Scrape 18225 Kühlungsborn (4 neue Portale)
    "oeffnungszeitenportal.de", "trauer.de", "deutschbranchenbuch.com", "statistikportal.de",
    "ohne-makler.net", "hausverwaltersuche.de", "ortsdienst.de", "bid-coburg.de",
    # 21:16 09.02.2026: Rostock Portal-Scan
    "auskunft.de", "aok.de", "med-kolleg.de", "aponet.de", "wellnissimo.de",
    "optimalnachhilfe.de", "nachhilfeportal.de", "kleinanzeigen.de",
    "pizzeria.de", "smileys.de", "ubereats.com", "worldorgs.com",
    "tanzkurs.com", "trustedmusic.de", "prontopro.de", "yably.de", "metalflirt.de",
    "betreut.de", "tagesmutter-in-rostock.de", "erstekinderbetreuung.de",
    "11880-zahnarzt.com", "klick-deine-hundeschule.de", "musikschule-in-rostock.de",
    "deincateringportal.de", "hertz.de", "eismann.de", "durst.de",
    # 21:05 09.02.2026: Portal-Audit — 145 neue Portale (False Positives gefiltert)
    "abschleppdienst-24.com",
    "aenderungsschneidereiindernaehe.com",
    "aerzte.de",
    "anbieter.1a-immobilienmarkt.de",
    "anwalt-suchservice.de",
    "apollo.de",
    "apotheke-finden.com",
    "arzttermine.de",
    "auf-nach-mv.de",
    "autoplenum.de",
    "banzkow.defirmenkataloge.com",
    "bauportal-deutschland.de",
    "baustoffe-liefern.de",
    "berufsfotografen.com",
    "blumenladen.org",
    "bodenleger-portal.de",
    "boschcarservice.com",
    "branchenportal24.de",
    "bundesland-mecklenburg-vorpommern.stadtbranchenbuch.com",
    "business-branchenbuch.de",
    "cleanerportal.de",
    "clever-fit.com",
    "dachdecker-portal.de",
    "dein-hundefriseur.de",
    "der-hoerakustiker.de",
    "deutsches-krankenhaus-verzeichnis.de",
    "doctena.de",
    "dogorama.app",
    "dooggs.de",
    "dorf-mecklenburg.defirmenkataloge.com",
    "dorf-mecklenburg.stadtbranchenbuch.com",
    "druckereien.info",
    "ee-portal.eu",
    "fahrrad-online-verkaufen.de",
    "firmenabc.com",
    "fitnesscenter-24.com",
    "fressnapf.de",
    "gadebusch.defirmenkataloge.com",
    "gartenbau.org",
    "gastroguide.de",
    "genialokal.de",
    "gesund.de",
    "glaser-portal.de",
    "glaserei.org",
    "goldberg.defirmenkataloge.com",
    "handelsregister-online.de",
    "handwerkerportal24.eu",
    "hausmeisterdienste.net",
    "heizungsbau.net",
    "helios-gesundheit.de",
    "hno-aerzte-im-netz.de",
    "hochzeitsjournal.de",
    "hochzeitsportal24.de",
    "houzz.de",
    "hundeschulen-verzeichnis.com",
    "info-aerzte.de",
    "intersport.de",
    "it-dienstleister-guide.de",
    "ja.de",
    "jobs.nordex-online.com",
    "kfz-serviceportal.de",
    "kimeta.de",
    "kind.com",
    "kinderaerzte-im-netz.de",
    "kindertagespflege-finden.de",
    "kirche-mv.de",
    "kita.de",
    "kitanetz.de",
    "klempner-portal.de",
    "klier.de",
    "koomio.com",
    "kosmetikstudios-24.de",
    "kuehlungsborn.stadtbranchenbuch.com",
    "location-suchen.de",
    "maklersuchen.com",
    "maler-portal.de",
    "marktplatz-mittelstand.de",
    "marktplatz.bike",
    "maurer-portal.de",
    "maz-online.de",
    "medpertise.de",
    "medvergleich.de",
    "mein-augenarzt.org",
    "mein-monteurzimmer.de",
    "mein-schluesseldienst.org",
    "meinreisebuero24.com",
    "metallbau-portal.de",
    "model-kartei.de",
    "monteurzimmer.de",
    "nagelpflege-24.de",
    "nagelstudio-24.de",
    "neukloster.stadtbranchenbuch.com",
    "oeffnungszeitenbuch.de",
    "onlinestreet.de",
    "ostseebad-boltenhagen.stadtbranchenbuch.com",
    "ovb.de",
    "pedali.de",
    "pension.de",
    "petnews.de",
    "pflegesuche.de",
    "piste.de",
    "pkw.de",
    "preiswert-uebernachten.de",
    "ra.de",
    "raabkarcher.de",
    "raumausstatter-portal.de",
    "regional-hundeschule.de",
    "rostock-branchenbuch.de",
    "rostock.branchen-info.net",
    "rostock.city-map.de",
    "schuelerhilfe.de",
    "schwerin-sn.branchen-info.net",
    "see-it-service.de",
    "seniorenportal.de",
    "sicherheitsdienstleister-deutschland.de",
    "speisekarte.de",
    "speisekarte.menu",
    "steuerberaterportal24.eu",
    "stores.deichmann.com",
    "study-in-germany-info.de",
    "suche-einen-steuerberater.de",
    "suchehandwerker.de",
    "tattoola.de",
    "threebestrated.de",
    "tierarzt-onlineverzeichnis.de",
    "tierarzt24.de",
    "tierarztsuche.tiergesund.de",
    "tipaw.com",
    "torten.org",
    "trainingsland.de",
    "trauring.de",
    "uebersetzernetzwerk.net",
    "uebersetzungsbueros.net",
    "unternehmensverzeichnis.org",
    "verzeichnis.maklerzentrale.com",
    "viamichelin.de",
    "waescherei-suche.de",
    "wer-zu-wem.de",
    "whofinance.de",
    "wirsindhandwerk.de",
    "wismar.stadtbranchenbuch.com",
    "wittenburg.defirmenkataloge.com",
    "wlw.de",
    "xn--apotheke-in-der-nhe-finden-whc.de",
    "zahnarzt-preisvergleich.com",
    # 21:32 09.02.2026: Rostock Qualitätsprüfung — Portale die Gemini-Calls verschwenden
    "cylex.de",
    "creditreform.de",
    "finde-offen.de",
    "autovermietung.adac.de",
    "century21.de",
    "juwelind.de",
    "tutorspace.de",
    "abschleppservice.org",
    "klick-dein",  # klick-deine-zoohandlung.de, klick-deinen-copyshop.de, etc.
    "kuechen-atlas.de",
    "kuechen-forum.de",
    "mahnerfolg.de",
    "meinmacher.de",
    "phone-base.de",
    "expertiger.de",
    "kaputt.de",
    "handyreparaturvergleich.de",
    "guenstig-umzugsunternehmen.de",
    "umzugsfirmen-check.de",
    "umzug-365.de",
    "weekli.de",
    "bgt-jur.de",
    "it-service.network",
    "druckereien.com.de",
    "investorenportal-mv.de",
    "wertgarantie.de",
    "rostock-nachhaltig.de",
    "notar-in-rostock.de",
    # 21:48 09.02.2026: Bad Doberan Portal-Scan (49 neue Portale)
    "autovermietungen.com.de",
    "notare.com.de",
    "schluesseldienstrostock.de",
    "apex-schaedlingsbekaempfung.de",
    "baddoberan.city-map.de",
    "stocksfloor-vs.de",
    "cityface.at",
    "deco.de",
    "die-aufsperrengel.de",
    "fensterbauer-regional.de",
    "glas.de",
    "hundeschulen.derhund.de",
    "luckykids.de",
    "mannstaedt.net",
    "mapcarta.com",
    "schluesselnotdienst.com",
    "sommer-kammerjaeger.de",
    "tanzschule.rocks",
    "toplocalplaces.com",
    "topnanny.de",
    "vogel.reifenhandel.com",
    "autoglaser.de",
    "citysports.de",
    "designermoebelmarkt.de",
    "ebike-mott.de",
    "fahrradreparatur.org",
    "friseurenet.de",
    "hundund.de",
    "ihr-schuh-shop.de",
    "kammerjaeger-flink.de",
    "kammerjaeger-vorort.de",
    "kleeo.de",
    "mapquest.com",
    "musiker-sucht.de",
    "musikschule.info",
    "platinschmuck.de",
    "regional.de",
    "schadstoffmobil24.de",
    "schlosserei.net",
    "schluesseldienst-bad-doberan.com",
    "schluesseldienst-flink.de",
    "schneidereien.net",
    "schuhe.de",
    "schule-und-spass.de",
    "special-e.de",
    "tuugo.de",
    "uebersetzungen-72.de",
    "uhren-schmuck.de",
    "unfallgiganten.de",
    # 22:16 09.02.2026: Portale aus Kühlungsborn/Raben Steinfeld Qualitäts-Check
    "terminbuchen.de", "nagelstudio.org", "nagelstudio-gesucht.de",
    "meinhoergeraet.de", "ihr-hoergeraet.de", "hoergeraete.die-endverbraucher.de",
    "fresha.com", "bioladen.de", "beautyheldin.de", "babysitter.de",
    "elektriker24.org", "sport-branchenbuch.de", "immowelt.de",
    "therapeutenfinder.com", "heilpraktiker-direktsuche.de", "thelabelfinder.de",
    "hundeschulen.de", "hundeatlas.com", "kosmetikstudios.com.de",
    "findedeinyoga.org", "agila.de", "kuehlungsborn.de",
    # 22:31 09.02.2026: Portale aus Leezen/Kühlungsborn Qualitäts-Check
    "city-advisor.de", "finanzamt24.de", "putzperle.de", "daibau.de",
    "daemmen-und-sanieren.de", "umzugsfirma-angebote.de", "autobutler.de",
    "mueller-entruempelung.de", "rudi-ruempel.de", "mrcleaner.de", "finde.de",
    "raumausstatter.biz", "regiohandwerker.de", "hausmeisterservice-segeberg.de",
    "facilitymanagement.org", "haus-experten.org", "adressennet.de",
    "sicherheitsdienst-24h.de", "proprate.de", "immonet.de", "notglaserei.de",
    "abfallscout.de", "strassenbauportal.de", "der-klempner-24.de",
    "profi-klempner.de", "rohrreinigung-24std.de", "rohrstar.de",
    "rohrreinigung-eberhardt.de", "rohrreinigung-vorort.de", "rohrblitz24.de",
    "bauer-rohrreinigung.de", "not-am-rohr.de", "rohrreinigung.online",
    "rohrreinigung-hartmut.de", "mein-heizung-profi.de",
    # 23:31 09.02.2026: MASSIVE Portal-Erweiterung (Qualitätsprüfung Full-Scraper)
    "citymap-24.com", "hochzeitsspeicher.de", "die-ideale-brautmode.de",
    "lampe-webdesigner.de", "virtualx.de", "die-webseiten-macher.de",
    "webdesign-kall.de", "sandeck.media", "daniel-wom.de",
    "merryll-webdesign.de", "web-shop-gestaltung.de", "kreativ-webagentur.de",
    "storefitting.com", "in-berlin-brandenburg.com", "bark.com",
    "servicepoint.de", "der-elektriker-24.de", "mein-elektriker-profi.de",
    "elektroservice-plus.de", "ksc-elektro.de", "kuechenfinder.com",
    "cleverkuechenkaufen.de", "gruppenunterkuenfte.de", "7f.com",
    "1000ferienwohnungen.de", "ferienhausmiete.de", "hometogo.de",
    "deinzimmer.de", "hofentdecker.arlafoods.de", "regiothek.de",
    "congendo.com", "eventcompanies.de", "mein-bauernhof.de",
    "deineventdj.de", "diskjockey-in.de", "seen.de",
    "ruhedirekt.de", "baumbestattung.org", "druckanfragen24.com",
    "lokalwissen.de", "containerdienstvorort.de", "agentur.de",
    "wasserhaerte.net", "onlineagentur-mueller.de", "scresign.de",
    "webseiten-erstellung-experte.de", "gasflasche.de", "supermarktlieferservices.de",
    "cleanolia.de", "elektriker-vorort.de", "ferienhaus-liste.de",
    "ich-tanke.de", "kiesdirekt.de", "fewo24.de",
    "ferienundwohnen.de", "sanego.de", "hausarztgo.com",
    "reisebuero-finden.com", "gelenkexperten.com", "arzt-atlas.de",
    "portal-der-augenmedizin.de", "einrichten-wohnen-leben.de", "mehr-tanken.de",
    "mein-gaertner.eu", "weisse-liste.de", "dachreinigung-talent.de",
    "schluesseldienst-karl.de", "autoboerse.de", "bikeundco.de",
    "deutschland-navigator.de", "suche-postleitzahl.org", "firmenschau.com",
    "stadtstiefel.de", "restablo.de", "pizza-taxi.de",
    "online-pizza.de", "restaurant.info", "wheree.com",
    "allekommen.com", "restaurant-reservieren-lieferservice.de", "klinikheld.com",
    "my-tischler.de", "worldpostalcodes.org", "klimatechniker.net",
    "maurer-und-betonbauer.de", "mein-dachdecker-profi.de", "hochtiefbau.net",
    "viermalw.eu", "branchen-info.net", "weg.li", "getaround.com",
    # 23:46 09.02.2026: Nachtschicht-Qualitätsprüfung
    "stadtplan.net", "haendlerschutz.com", "reinigungsverzeichnis.de",
    "germany4ukraine.de", "36bestatter.com",
    # 00:05 10.02.2026: Wittenförden/Witten Scrape — 20 neue Portale aus Qualitätsprüfung
    "1a-sanitaerservice.de", "11880-gebaeudereinigung.com", "11880-versicherung.com",
    "abschleppdienst-hilfe.de", "abschleppdienst-neumann.de", "autoteam24.info",
    "bad-eigenheim.de", "bauunternehmen-liste.de", "dialo.de",
    "ferienwohnungen-", "happycar.de", "hofladen-bauernladen.info",
    "hundetrainer.info", "installateur-mv.de", "klempner-vorort.de",
    "rohrreinigung-", "sanitaer-und-heizungsbau.com", "stadte-gemeinden.de",
    "trustlocal.de", "versicherung-en.de", "wh-autozentrum.de",
    # 00:16 10.02.2026: Rastow/Banzkow Full-Scrape — 57 neue Portale aus Qualitätsprüfung
    "kompass.com", "indernaehe.eu", "waschmal.de", "heizoel24.de", "stoffstrom.org",
    "az-deutschland.com", "med-doc24.com", "veteri.de", "findcity.de", "tierarztgo.com",
    "tierarzt-finden.org", "tierarzt-in-der-naehe.de", "yorkie-hundeforum.com",
    "postalcodeguide.com", "tierheim-verzeichnis.de", "allefotografen.de", "geonum.de",
    "deutschebusiness.com", "deutscheshoponline.com", "kimbino.de", "trovit.com",
    "listando.de", "friseure.com.de", "firmenportal.de", "firmenwissen.com", "hagos.de",
    "tankbillig.info", "strassen.openalfa.de", "medienkaiser.de", "airpaz.com",
    "50plus.faz.net", "finest-jobs.com", "reinigungstechnik.me",
    "graalmueritz-ferienwohnung.de", "hotel-mix.de", "reisebuero-webseite.de",
    "gerichtsstand.net", "bring-together.de", "meldeaemter.de", "36notare.com",
    "xn--ffnungszeit-qfb.net", "bringbutler.de", "telefonbucher.de", "getcater.de",
    "die-ideale-tanzschule.de", "reservieren.com", "biogefluegelhandel.de",
    "facharztsuche.net", "outdooractive.com", "wikidata.org", "implisense.com",
    "markt.de", "kindergarten.info", "schlaganfall-info.de", "psychomeda.de",
    "coparking.ch", "kitchenadvisor.de",
    "klicktel.de",
    "portal-der-haut.de",
    "verwaltungsportal.eu",
    "muenchen.de",
    "portal-grundbuchamt.de",
]
